### ISSUE TITLE
ERROR: java.lang.ClassNotFoundException: jazzer_clojure_example.targets.SimpleExample

### ISSUE THREAD

**Issue by luigigubello** [CodeIntelligenceTesting/jazzer-clojure-example#1]
Hi :wave: probably this error is trivial and easy to fix, but I don't understand it. I am trying to reproduce the example, I run `lein uberjar` to create the standalone JAR, then I launch Jazzer. Instead of using the Docker container, I prefer to use the binary, so I run:

```
./jazzer target/jazzer-clojure-example-0.1.0-SNAPSHOT-standalone.jar --target-class=jazzer_clojure_example.targets.SimpleExample
```

But it returns always 

```
ERROR: java.lang.ClassNotFoundException: jazzer_clojure_example.targets.SimpleExample
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at com.code_intelligence.jazzer.driver.FuzzTargetRunner.<clinit>(FuzzTargetRunner.java:91)
	at com.code_intelligence.jazzer.driver.Driver.start(Driver.java:88)
```

What am I wrong? Thanks in advance

**Environment:**
Ubuntu 22.04
Clojure CLI version 1.11.1.1155
openjdk version "17.0.4.1" 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)
Leiningen 2.9.10 on Java 17.0.4.1 OpenJDK 64-Bit Server VM

**Comment by fmeum** [comment]
You have to prefix the path to the jar with `--cp=`. Could you try that?

**Comment by luigigubello** [comment]
I knew it was a trivial mistake. Thanks for your reply :heart:
